// src/app/blogs/[slug]/page.tsx
// ── Dynamic Blog Post Page ───────────────────────────────────
//
// SEO Best Practices demonstrated here:
// 1. generateStaticParams()   → pre-renders all posts at build time (SSG)
// 2. generateMetadata()       → unique title, description, OG per post
// 3. Article JSON-LD          → rich results in Google
// 4. <time> with dateTime     → semantic publish date
// 5. Canonical URL per post
// 6. Proper H1 → H2 hierarchy
//
// FUTURE: Replace the `posts` array with a CMS call like:
//   const post = await sanityClient.fetch(groq`*[slug.current == $slug][0]`, { slug })
// ──────────────────────────────────────────────────────────────

import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { generateArticleMetadata, generateArticleJsonLd, SITE_CONFIG } from '@/lib/seo';
import Link from 'next/link';
import ScrollReveal from '@/app/components/ScrollReveal';
import { ArrowLeft, Clock, Calendar } from 'lucide-react';

// ── Static post data (replace with CMS fetch in production) ──
const posts: Record<string, {
  slug: string; title: string; excerpt: string; content: string;
  category: string; author: string; publishedAt: string; readTime: string; tags: string[];
}> = {
  'why-brand-identity-matters': {
    slug:        'why-brand-identity-matters',
    title:       'Why Brand Identity Is Your Most Valuable Business Asset',
    excerpt:     'Most companies treat brand as a cost centre. The best ones understand it\'s a compounding investment that reduces acquisition costs and increases lifetime value.',
    content:     `Brand identity is not logo design. It's not a colour palette or a style guide. Brand identity is the sum of every signal your company emits — visual, verbal, behavioural — and the feeling those signals create in the minds of the people you're trying to reach.

The companies that understand this treat brand as infrastructure. They invest in it with the same rigour they invest in product, engineering, or sales. Because they know what the data consistently shows: strong brands command price premiums, attract better talent, and retain customers longer.

Consider the economics. Customer acquisition costs have risen roughly 60% in the last five years. In that environment, every existing customer who stays, every prospect who chooses you over a cheaper alternative, every referral generated by genuine affinity — these have compounding financial value.

Brand is the mechanism by which all of this becomes possible.

**What makes a brand identity strong?**

Clarity. Distinctiveness. Consistency. And emotional resonance. In that order.

Clarity means your positioning is singular and defensible. You know exactly who you're for and why they should choose you. Distinctiveness means you look, sound, and feel unlike anyone in your category. Consistency means that signal is reliable across every touchpoint. And emotional resonance means the sum of all of it connects at a level beyond rational justification.

Most brands achieve none of these. They're underdifferentiated, visually forgettable, and emotionally inert. Which is actually good news — because the bar is low, and standing above it is available to almost everyone willing to commit.`,
    category:    'Brand Strategy',
    author:      'Elena Vasquez',
    publishedAt: '2025-04-08',
    readTime:    '7 min read',
    tags:        ['Branding', 'Strategy', 'Business'],
  },
  'designing-for-premium-audiences': {
    slug:        'designing-for-premium-audiences',
    title:       'How to Design for Premium Audiences Without Alienating Everyone Else',
    excerpt:     'Premium positioning isn\'t about being exclusive — it\'s about communicating quality so clearly that the right people self-select.',
    content:     `There's a persistent myth in design that premium means minimalist, cold, and distant. That luxury aesthetics require emptiness and reserve. That if something feels warm or accessible, it can't be positioned at the top of its market.

This is wrong — and it's costing brands that believe it.

Premium positioning is about **perceived value**. And perceived value is shaped by quality signals, not by emotional withdrawal. The most admired luxury brands in the world are deeply emotionally engaging. They make you feel something. That feeling is just carefully curated, considered, and consistent.

**What does premium actually look like?**

It looks like craft. Attention to detail at the micro level — the spacing between letters, the weight of a line, the way a hover state resolves. These sub-perceptual signals aggregate into an overall impression of care and quality.

It sounds like confidence. Premium brands don't hedge. Their copy is direct, specific, and unafraid. They know exactly who they're talking to and they talk to them without qualification.

It feels like respect for the audience's intelligence. No dark patterns. No manipulation. No artificial urgency. Just honest communication delivered with precision.

Premium design doesn't exclude people. It attracts the right ones by making quality undeniable.`,
    category:    'Design',
    author:      'James Holt',
    publishedAt: '2025-04-01',
    readTime:    '5 min read',
    tags:        ['Design', 'UX', 'Premium'],
  },
  'seo-for-creative-agencies': {
    slug:        'seo-for-creative-agencies',
    title:       'SEO for Creative Agencies: A Practical Field Guide',
    excerpt:     'Most agencies build beautiful websites for clients but neglect their own SEO. Here\'s the playbook we use — and give away freely.',
    content:     `Creative agencies are often the worst at marketing themselves. We spend months crafting perfect digital experiences for clients and then build our own websites with zero consideration for how they'll be found.

This is a structural problem. SEO feels unglamorous. It's slow. The results aren't visible the way a beautiful design is visible. But in a market where attention is scarce and paid acquisition is expensive, organic search is one of the highest-leverage investments a service business can make.

Here's the framework we use internally, and recommend to every agency we work with.

**1. Define your keyword universe**

Start with the work you want to do. Not the work you've done — the work you want to attract. Map those services to search queries your ideal clients actually use. 'Brand identity agency London', 'UI/UX studio for fintech', 'website design for professional services' — specific, intent-rich phrases.

**2. Build content that earns the ranking**

Google ranks pages that genuinely answer the searcher's question better than alternatives. That means going deep. A 300-word service page won't rank. A 2,000-word guide that explains exactly how you approach brand strategy, includes examples, and answers objections — that earns rankings.

**3. Make every page technically sound**

Fast loading (sub 3 seconds). Mobile-first. Semantic HTML. Proper heading hierarchy. Every image with alt text. A sitemap that's submitted to Google Search Console. These aren't optional — they're the floor.

**4. Build authority through genuine thought leadership**

Links from relevant publications, podcasts, and communities signal authority to Google. You earn them by publishing ideas worth citing. Which means having ideas, and writing them well. Not posting for algorithms — writing for people.

**5. Measure what matters**

Organic traffic growth. Keyword rank position over time. Leads attributed to organic search. These are the metrics that tell you if your investment is working.`,
    category:    'Growth',
    author:      'Priya Nair',
    publishedAt: '2025-03-20',
    readTime:    '9 min read',
    tags:        ['SEO', 'Marketing', 'Agency Growth'],
  },
};

// ── 1. generateStaticParams: pre-render all blog posts at build ──
export async function generateStaticParams() {
  return Object.keys(posts).map((slug) => ({ slug }));
}

// ── 2. generateMetadata: unique SEO per post ─────────────────
export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const post = posts[params.slug];
  if (!post) return { title: 'Post Not Found' };

  return generateArticleMetadata({
    title:       post.title,
    description: post.excerpt,
    slug:        post.slug,
    publishedAt: post.publishedAt,
    author:      post.author,
    tags:        post.tags,
  });
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
}

export default function BlogPostPage({ params }: { params: { slug: string } }) {
  const post = posts[params.slug];
  if (!post) notFound();

  // ── 3. Article JSON-LD for rich results ──────────────────
  const articleJsonLd = generateArticleJsonLd({
    title:       post.title,
    description: post.excerpt,
    slug:        post.slug,
    publishedAt: post.publishedAt,
    author:      post.author,
  });

  const paragraphs = post.content.split('\n\n').filter(Boolean);

  return (
    <>
      {/* Inject Article JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />

      {/* ── Back link ── */}
      <div className="max-w-3xl mx-auto px-6 pt-36 pb-4">
        <Link
          href="/blogs"
          className="inline-flex items-center gap-2 text-muted hover:text-gold text-sm transition-colors duration-300"
        >
          <ArrowLeft size={14} /> Back to Blogs
        </Link>
      </div>

      {/* ── Article Header ── */}
      <article
        aria-labelledby="article-heading"
        className="max-w-3xl mx-auto px-6 pb-24"
      >
        <header className="mb-12 pt-6">
          <ScrollReveal>
            <div className="flex items-center gap-3 mb-6">
              <span className="px-3 py-1 bg-[rgba(201,169,110,0.08)] border border-[rgba(201,169,110,0.15)] text-gold text-xs font-medium tracking-wider rounded-sm">
                {post.category}
              </span>
              <span className="flex items-center gap-1 text-faint text-xs">
                <Clock size={11} /> {post.readTime}
              </span>
            </div>

            {/* ── H1: most important SEO element ── */}
            <h1
              id="article-heading"
              className="font-display text-4xl md:text-5xl font-bold text-ivory leading-tight mb-6"
            >
              {post.title}
            </h1>

            <p className="text-muted text-lg leading-relaxed mb-8 border-l-2 border-gold/30 pl-5 italic">
              {post.excerpt}
            </p>

            <div className="flex items-center gap-6 py-6 border-y border-[rgba(255,255,255,0.06)]">
              <div className="w-10 h-10 rounded-full bg-bg-card border border-[rgba(201,169,110,0.2)] flex items-center justify-center">
                <span className="font-display text-sm text-gold font-bold">
                  {post.author.charAt(0)}
                </span>
              </div>
              <div>
                {/* ── rel="author" is an SEO signal ── */}
                <p className="text-ivory text-sm font-semibold" rel="author">{post.author}</p>
                <div className="flex items-center gap-3 text-faint text-xs mt-0.5">
                  <span className="flex items-center gap-1">
                    <Calendar size={10} />
                    {/* ── <time> with dateTime is semantic ── */}
                    <time dateTime={post.publishedAt}>{formatDate(post.publishedAt)}</time>
                  </span>
                  <span>·</span>
                  <span>{SITE_CONFIG.name}</span>
                </div>
              </div>
            </div>
          </ScrollReveal>
        </header>

        {/* ── Article Body ── */}
        {/* SEO: Content lives inside <article>, uses proper paragraph structure */}
        <div className="prose-custom">
          {paragraphs.map((para, i) => {
            if (para.startsWith('**') && para.endsWith('**')) {
              return (
                <ScrollReveal key={i} delay={0.05}>
                  <h2 className="font-display text-2xl font-semibold text-ivory mt-12 mb-4">
                    {para.replace(/\*\*/g, '')}
                  </h2>
                </ScrollReveal>
              );
            }
            return (
              <ScrollReveal key={i} delay={0.05}>
                <p className="text-muted leading-[1.9] mb-6 text-base">
                  {para}
                </p>
              </ScrollReveal>
            );
          })}
        </div>

        {/* ── Tags ── */}
        <ScrollReveal>
          <div className="flex flex-wrap gap-2 mt-12 pt-8 border-t border-[rgba(255,255,255,0.06)]">
            <span className="text-faint text-xs uppercase tracking-wider mr-2 flex items-center">Tags:</span>
            {post.tags.map(tag => (
              // FUTURE: Link these to a /blogs?tag=X filtered page
              <span key={tag} className="px-3 py-1 text-xs text-muted border border-[rgba(255,255,255,0.06)] rounded-sm hover:border-gold/20 hover:text-ivory transition-colors duration-300">
                {tag}
              </span>
            ))}
          </div>
        </ScrollReveal>

        {/* ── CTA ── */}
        <ScrollReveal delay={0.1}>
          <div className="mt-16 p-8 bg-bg-card border border-[rgba(201,169,110,0.1)] rounded-sm text-center">
            <p className="font-display text-xl font-semibold text-ivory mb-2">
              Ready to work together?
            </p>
            <p className="text-muted text-sm mb-6">
              Let's build something extraordinary for your brand.
            </p>
            <Link href="/#contact" className="btn-gold text-xs">
              Start a Project
            </Link>
          </div>
        </ScrollReveal>
      </article>
    </>
  );
}
